//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineConfig
    {
        public System.Guid AirlineConfigOID { get; set; }
        public string DepartureCode { get; set; }
        public string DestinationCode { get; set; }
        public Nullable<bool> IsInclude { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
