//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineControlSub
    {
        public System.Guid AirlineSubOID { get; set; }
        public System.Guid AirlineOID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AirlineCode { get; set; }
        public string ClassOfService { get; set; }
        public string FareBasis { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
