//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineControl
    {
        public System.Guid AirlineOID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OriginalCountryCode { get; set; }
        public string DestinationCountryCode { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
