//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIToken
    {
        public string Token { get; set; }
        public System.Guid APIUserOID { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
