//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIUser
    {
        public System.Guid APIUserOID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> WebMode { get; set; }
    }
}
