//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOfficeAdmin
    {
        public System.Guid BackOfficeAdminOID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Address { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
