//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingDBEntities : DbContext
    {
        public BookingDBEntities()
            : base("name=BookingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirlineCode> AirlineCodes { get; set; }
        public virtual DbSet<AirlineControl> AirlineControls { get; set; }
        public virtual DbSet<AirlineControlSub> AirlineControlSubs { get; set; }
        public virtual DbSet<AirlineQtaxControl> AirlineQtaxControls { get; set; }
        public virtual DbSet<AirportCode> AirportCodes { get; set; }
        public virtual DbSet<AirportLocation> AirportLocations { get; set; }
        public virtual DbSet<AirportTranfer> AirportTranfers { get; set; }
        public virtual DbSet<AirportWithCity> AirportWithCities { get; set; }
        public virtual DbSet<AirPromotion> AirPromotions { get; set; }
        public virtual DbSet<APIToken> APITokens { get; set; }
        public virtual DbSet<APIUser> APIUsers { get; set; }
        public virtual DbSet<BackOfficeAdmin> BackOfficeAdmins { get; set; }
        public virtual DbSet<ChillPayBackground> ChillPayBackgrounds { get; set; }
        public virtual DbSet<ChillPayInquiry> ChillPayInquiries { get; set; }
        public virtual DbSet<ChillPayResult> ChillPayResults { get; set; }
        public virtual DbSet<CityCode> CityCodes { get; set; }
        public virtual DbSet<CountryCode> CountryCodes { get; set; }
        public virtual DbSet<CurrencyExchange> CurrencyExchanges { get; set; }
        public virtual DbSet<FlightBookingBaggage> FlightBookingBaggages { get; set; }
        public virtual DbSet<FlightBookingContactInfo> FlightBookingContactInfoes { get; set; }
        public virtual DbSet<FlightBookingFare> FlightBookingFares { get; set; }
        public virtual DbSet<FlightBookingFareRule> FlightBookingFareRules { get; set; }
        public virtual DbSet<FlightBookingFareRuleDatail> FlightBookingFareRuleDatails { get; set; }
        public virtual DbSet<FlightBookingPaxInfo> FlightBookingPaxInfoes { get; set; }
        public virtual DbSet<FlightBookingRefund> FlightBookingRefunds { get; set; }
        public virtual DbSet<FlightBookingReissue> FlightBookingReissues { get; set; }
        public virtual DbSet<FlightSearchLog> FlightSearchLogs { get; set; }
        public virtual DbSet<FourDigitControl> FourDigitControls { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<KBankCharge> KBankCharges { get; set; }
        public virtual DbSet<PassportConfig> PassportConfigs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentReference> PaymentReferences { get; set; }
        public virtual DbSet<RunningNumber> RunningNumbers { get; set; }
        public virtual DbSet<SeatMapControl> SeatMapControls { get; set; }
        public virtual DbSet<HBHotelName> HBHotelNames { get; set; }
        public virtual DbSet<FlightFareRuleDetail> FlightFareRuleDetails { get; set; }
        public virtual DbSet<FlightFareRuleConfig> FlightFareRuleConfigs { get; set; }
        public virtual DbSet<AirlineConfig> AirlineConfigs { get; set; }
        public virtual DbSet<SiteConfig> SiteConfigs { get; set; }
        public virtual DbSet<FlightSearchMultiTicket> FlightSearchMultiTickets { get; set; }
        public virtual DbSet<FlightBookingFlightDetail> FlightBookingFlightDetails { get; set; }
        public virtual DbSet<DiscountTagDetail> DiscountTagDetails { get; set; }
        public virtual DbSet<FlightBooking> FlightBookings { get; set; }
        public virtual DbSet<DiscountTag> DiscountTags { get; set; }
        public virtual DbSet<PromotionGroupCode> PromotionGroupCodes { get; set; }
        public virtual DbSet<PaymentLog> PaymentLogs { get; set; }
        public virtual DbSet<FlightFareRule> FlightFareRules { get; set; }
        public virtual DbSet<MarkupFlight> MarkupFlights { get; set; }
    }
}
