//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChillPayInquiry
    {
        public System.Guid ChillPayInquiryID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string MerchantCode { get; set; }
        public string TransactionId { get; set; }
        public string ApiKey { get; set; }
        public string CheckSum { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> ChillPayBackgroundID { get; set; }
    }
}
