//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChillPayBackground
    {
        public System.Guid ChillPayBackgroundID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string TransactionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string OrderNo { get; set; }
        public string CustomerId { get; set; }
        public string BankCode { get; set; }
        public string PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public string BankRefCode { get; set; }
        public string CurrentDate { get; set; }
        public string CurrentTime { get; set; }
        public string PaymentDescription { get; set; }
        public string CreditCardToken { get; set; }
        public string Currency { get; set; }
        public string CheckSum { get; set; }
        public string ResponseType { get; set; }
    }
}
