//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSearchMultiTicket
    {
        public System.Guid FlightSearchOID { get; set; }
        public string FlightSearchRequest { get; set; }
        public string FlightSearchResponse { get; set; }
        public Nullable<System.DateTime> DateTimeRequest { get; set; }
    }
}
