//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBookingFlightDetail
    {
        public System.Guid FlightBookingFlightDetailOID { get; set; }
        public System.Guid BookingOID { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public string FlightTime { get; set; }
        public string ConnectingTime { get; set; }
        public string Rbd { get; set; }
        public string FareBasis { get; set; }
        public Nullable<int> AvailableSeat { get; set; }
        public string FareType { get; set; }
        public string Cabin { get; set; }
        public string EquipmentType { get; set; }
        public string DepCity { get; set; }
        public string ArrCity { get; set; }
        public string Airline { get; set; }
        public string OperatedAirline { get; set; }
        public string TripType { get; set; }
        public Nullable<int> Seq { get; set; }
        public string ControlNumber { get; set; }
    }
}
