//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBookingBaggage
    {
        public System.Guid FlightBookingBaggageOID { get; set; }
        public System.Guid FlightBookingFareOID { get; set; }
        public string Baggages { get; set; }
        public string BaggageNo { get; set; }
        public string BaggageUnit { get; set; }
    }
}
