//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBookingRefund
    {
        public System.Guid FlightBookingRefundOID { get; set; }
        public System.Guid BookingOID { get; set; }
        public Nullable<int> Status { get; set; }
        public string NewPNR { get; set; }
        public string RefundNo { get; set; }
        public Nullable<System.DateTime> RefundCreateDate { get; set; }
        public Nullable<System.DateTime> RefundGMDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DueDateOfRefund { get; set; }
        public string OldPNR { get; set; }
    }
}
