//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightFareRuleDetail
    {
        public System.Guid FareRuleOID { get; set; }
        public string LanguageCode { get; set; }
        public string FareFamilyName { get; set; }
        public string FareRule { get; set; }
    }
}
