//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBookingFare
    {
        public System.Guid FlightBookingFareOID { get; set; }
        public System.Guid BookingOID { get; set; }
        public string PessengerType { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> SellingBaseFare { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Qtax { get; set; }
        public Nullable<decimal> LessFare { get; set; }
        public Nullable<decimal> Net { get; set; }
    }
}
