//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSearchLog
    {
        public System.Guid FlightSearchLog1 { get; set; }
        public string From1 { get; set; }
        public string From2 { get; set; }
        public string From3 { get; set; }
        public string From4 { get; set; }
        public string From5 { get; set; }
        public string From6 { get; set; }
        public string To1 { get; set; }
        public string To2 { get; set; }
        public string To3 { get; set; }
        public string To4 { get; set; }
        public string To5 { get; set; }
        public string To6 { get; set; }
        public string TripType { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<int> NoOfAdult { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public Nullable<int> NoOfInfant { get; set; }
        public string SeatClass { get; set; }
        public string AirlinePreference { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
    }
}
