//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBookingReissue
    {
        public System.Guid FlightBookingReissueOID { get; set; }
        public System.Guid BookingOID { get; set; }
        public Nullable<int> Status { get; set; }
        public string NewPNR { get; set; }
        public Nullable<System.DateTime> ReissueCreateDate { get; set; }
        public Nullable<int> TypeChage { get; set; }
        public Nullable<int> DetailChage { get; set; }
        public string Remark { get; set; }
    }
}
