//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HBHotelName
    {
        public int HotelCode { get; set; }
        public string DestinationCode { get; set; }
        public string CountryCode { get; set; }
        public string HotelName { get; set; }
        public string LanguageCode { get; set; }
    }
}
