//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KBankCharge
    {
        public string ChargeID { get; set; }
        public string transaction_state { get; set; }
        public string ref1 { get; set; }
        public string ref2 { get; set; }
        public string status { get; set; }
        public string message { get; set; }
        public string mode { get; set; }
    }
}
