//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentOID { get; set; }
        public Nullable<decimal> BankTranferValue { get; set; }
        public Nullable<decimal> KbankFullValue { get; set; }
        public Nullable<decimal> KbankInstallValue { get; set; }
        public Nullable<decimal> PaySolutionCounterValue { get; set; }
        public Nullable<decimal> PaySolutionInstallValue { get; set; }
        public Nullable<decimal> UnionpayValue { get; set; }
        public Nullable<bool> IspercentBankTranfer { get; set; }
        public Nullable<bool> IspercentKbankFull { get; set; }
        public Nullable<bool> IspercentKbankInstall { get; set; }
        public Nullable<bool> IspercentPayCouter { get; set; }
        public Nullable<bool> IspercentPayInstall { get; set; }
        public Nullable<bool> IIspercentUnionpay { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
