//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLog
    {
        public System.Guid PaymentLogOID { get; set; }
        public string RobinhoodID { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public string LogRequest { get; set; }
        public string LogResponse { get; set; }
    }
}
