//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionGroupCode
    {
        public System.Guid PromotionGroupCodeOID { get; set; }
        public string PromotionGroupCode1 { get; set; }
        public string PromotionGroupDescription { get; set; }
    }
}
