//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteConfig
    {
        public System.Guid ConfigOID { get; set; }
        public Nullable<int> Seq { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigValue { get; set; }
    }
}
