//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPromotion
    {
        public System.Guid AirPromotionOID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> DepartDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public string DeepLinkText { get; set; }
        public string AirlineCode { get; set; }
    }
}
