//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportWithCity
    {
        public string AirportCode { get; set; }
        public string FacilityCode { get; set; }
        public string CityCode { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string CountryCode { get; set; }
        public string IsCommercialAirport { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceCountryCode { get; set; }
    }
}
