//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GogojiiWebDBEntities : DbContext
    {
        public GogojiiWebDBEntities()
            : base("name=GogojiiWebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FlightSearchLog> FlightSearchLogs { get; set; }
        public virtual DbSet<AirlineCode> AirlineCodes { get; set; }
        public virtual DbSet<AirportCode> AirportCodes { get; set; }
        public virtual DbSet<AirportWithCity> AirportWithCities { get; set; }
        public virtual DbSet<CityCode> CityCodes { get; set; }
        public virtual DbSet<CountryCode> CountryCodes { get; set; }
        public virtual DbSet<AirPromotion> AirPromotions { get; set; }
        public virtual DbSet<ShortenURL> ShortenURLs { get; set; }
    }
}
